[tool.poetry]
name = "pytohchi"
version = "0.1.0"
description = ""
authors = ["z0ff <ex1999@msn.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ginza = "^5.1.3"
ja-ginza = "^5.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
